/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.BoxLayout;
import static javax.swing.BoxLayout.Y_AXIS;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionListener;
import princetonPlainsboro.*;

/**
 *
 * @author Cyril
 */
public class Fenetre extends javax.swing.JFrame {

    /*Pour le bouton Ajouter de Patient*/
    ArrayList<Patient> patients = new ArrayList<Patient>();
    DefaultListModel<String> dlmPat = new DefaultListModel<String>();

    /*Pour le bouton Ajouter de Medecin*/
    ArrayList<Medecin> medecins = new ArrayList<Medecin>();
    DefaultListModel<String> dlmMed = new DefaultListModel<String>();

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        importPatientFromXML();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        fenetre = new javax.swing.JPanel();
        menu = new javax.swing.JTabbedPane();
        patient = new javax.swing.JPanel();
        ajoutPatients = new javax.swing.JPanel();
        nom = new javax.swing.JLabel();
        ss = new javax.swing.JLabel();
        adresse = new javax.swing.JLabel();
        wnomPatient = new javax.swing.JTextField();
        wssPatient = new javax.swing.JTextField();
        wadresse = new javax.swing.JTextField();
        prenom = new javax.swing.JLabel();
        wprenomPatient = new javax.swing.JTextField();
        ajouterPatient = new javax.swing.JButton();
        listeDePatients = new javax.swing.JPanel();
        listePatients = new javax.swing.JScrollPane();
        listepatient = new javax.swing.JList();
        ficheSoinPatient = new javax.swing.JButton();
        modifierPatient1 = new javax.swing.JButton();
        recherchePatient = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        consulterPatient = new javax.swing.JButton();
        medecin = new javax.swing.JPanel();
        ajoutPatients1 = new javax.swing.JPanel();
        nom1 = new javax.swing.JLabel();
        adresse1 = new javax.swing.JLabel();
        wnomMedecin = new javax.swing.JTextField();
        wTelMedecin = new javax.swing.JTextField();
        wSpeMedecin = new javax.swing.JTextField();
        prenom1 = new javax.swing.JLabel();
        wprenomMedecin = new javax.swing.JTextField();
        ajouterMedecin = new javax.swing.JButton();
        ss2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        wIdentifiantMedecin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        wMDPMedecin = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        consulterMedecin = new javax.swing.JButton();
        modifierMedecin = new javax.swing.JButton();
        recherchePatient1 = new javax.swing.JButton();
        Rechercher = new javax.swing.JTextField();
        listePatients1 = new javax.swing.JScrollPane();
        listemedecin = new javax.swing.JList();
        soin = new javax.swing.JPanel();
        ajoutDeSoins = new javax.swing.JPanel();
        dateSoin = new javax.swing.JLabel();
        medecinSoin = new javax.swing.JLabel();
        patientSoin = new javax.swing.JLabel();
        wDateActe = new javax.swing.JTextField();
        wMedeinActe = new javax.swing.JTextField();
        actesSoin = new javax.swing.JLabel();
        ajouterSoin = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        infosPatient = new javax.swing.JTextArea();
        listeDeSoins = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listesoin = new javax.swing.JList();
        triSoin = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        consulterSoin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DateArrivee = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        dateDepart = new javax.swing.JTextField();
        modifierSoin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Actes = new javax.swing.JPanel();
        gh = new javax.swing.JPanel();
        listeDesActes = new javax.swing.JLabel();
        listeActes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        nouveauCoutActe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        validerCout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        listeDesActes1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CoutDuNouvelActe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        validerCout1 = new javax.swing.JButton();
        nomDuNouvelActe = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ajoutPatients.setBackground(new java.awt.Color(255, 255, 255));
        ajoutPatients.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), null));

        nom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nom.setText("Nom");

        ss.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ss.setText("n° Sécu");

        adresse.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adresse.setText("Adresse");

        wnomPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wnomPatientActionPerformed(evt);
            }
        });

        wssPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wssPatientActionPerformed(evt);
            }
        });

        prenom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prenom.setText("Prénom");

        ajouterPatient.setText("+ Ajouter");
        ajouterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajoutPatientsLayout = new javax.swing.GroupLayout(ajoutPatients);
        ajoutPatients.setLayout(ajoutPatientsLayout);
        ajoutPatientsLayout.setHorizontalGroup(
            ajoutPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutPatientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajoutPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoutPatientsLayout.createSequentialGroup()
                        .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wadresse))
                    .addGroup(ajoutPatientsLayout.createSequentialGroup()
                        .addGroup(ajoutPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ajoutPatientsLayout.createSequentialGroup()
                                .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wssPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ajoutPatientsLayout.createSequentialGroup()
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wnomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wprenomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 176, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajoutPatientsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ajouterPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ajoutPatientsLayout.setVerticalGroup(
            ajoutPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutPatientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajoutPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wnomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wprenomPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajoutPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wssPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajoutPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wadresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ajouterPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listeDePatients.setBackground(new java.awt.Color(255, 255, 255));
        listeDePatients.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), null));

        listePatients.setViewportView(listepatient);

        ficheSoinPatient.setText("+ Fiche de Soin");
        ficheSoinPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficheSoinPatientActionPerformed(evt);
            }
        });

        modifierPatient1.setText("Modifier");
        modifierPatient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierPatient1ActionPerformed(evt);
            }
        });

        recherchePatient.setText("O");
        recherchePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recherchePatientActionPerformed(evt);
            }
        });

        consulterPatient.setText("Consulter");
        consulterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterPatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listeDePatientsLayout = new javax.swing.GroupLayout(listeDePatients);
        listeDePatients.setLayout(listeDePatientsLayout);
        listeDePatientsLayout.setHorizontalGroup(
            listeDePatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeDePatientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listeDePatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(listeDePatientsLayout.createSequentialGroup()
                        .addComponent(recherchePatient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(listeDePatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ficheSoinPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consulterPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifierPatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listeDePatientsLayout.setVerticalGroup(
            listeDePatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeDePatientsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(listeDePatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(listeDePatientsLayout.createSequentialGroup()
                        .addGroup(listeDePatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recherchePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(listePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(listeDePatientsLayout.createSequentialGroup()
                        .addComponent(modifierPatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ficheSoinPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consulterPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout patientLayout = new javax.swing.GroupLayout(patient);
        patient.setLayout(patientLayout);
        patientLayout.setHorizontalGroup(
            patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajoutPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listeDePatients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        patientLayout.setVerticalGroup(
            patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajoutPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listeDePatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.addTab("Patients", patient);

        ajoutPatients1.setBackground(new java.awt.Color(255, 255, 255));
        ajoutPatients1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), null));

        nom1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nom1.setText("Nom");

        adresse1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adresse1.setText("Spécialité");

        wTelMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wTelMedecinActionPerformed(evt);
            }
        });

        prenom1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prenom1.setText("Prénom");

        ajouterMedecin.setText("+ Ajouter");
        ajouterMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterMedecinActionPerformed(evt);
            }
        });

        ss2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ss2.setText("Tel");

        jLabel11.setText("Identifiant");

        jLabel12.setText("MdP");

        javax.swing.GroupLayout ajoutPatients1Layout = new javax.swing.GroupLayout(ajoutPatients1);
        ajoutPatients1.setLayout(ajoutPatients1Layout);
        ajoutPatients1Layout.setHorizontalGroup(
            ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutPatients1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajouterMedecin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ajoutPatients1Layout.createSequentialGroup()
                        .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ajoutPatients1Layout.createSequentialGroup()
                                .addComponent(nom1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wnomMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prenom1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wprenomMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ajoutPatients1Layout.createSequentialGroup()
                                    .addComponent(ss2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(wTelMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ajoutPatients1Layout.createSequentialGroup()
                                    .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addComponent(adresse1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                    .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ajoutPatients1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(wSpeMedecin))
                                        .addGroup(ajoutPatients1Layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(ajoutPatients1Layout.createSequentialGroup()
                                                    .addComponent(wIdentifiantMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addComponent(wMDPMedecin)))))))
                        .addGap(0, 176, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ajoutPatients1Layout.setVerticalGroup(
            ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutPatients1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wnomMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenom1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wprenomMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wTelMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ss2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresse1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wSpeMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(wIdentifiantMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoutPatients1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ajouterMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wMDPMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), null));

        consulterMedecin.setText("Consulter");
        consulterMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterMedecinActionPerformed(evt);
            }
        });

        modifierMedecin.setText("Modifier");
        modifierMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierMedecinActionPerformed(evt);
            }
        });

        recherchePatient1.setText("O");
        recherchePatient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recherchePatient1ActionPerformed(evt);
            }
        });

        Rechercher.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        Rechercher.setForeground(new java.awt.Color(204, 204, 204));
        Rechercher.setText("Rechercher");

        listePatients1.setViewportView(listemedecin);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(listePatients1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifierMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consulterMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(recherchePatient1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recherchePatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(modifierMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(consulterMedecin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listePatients1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout medecinLayout = new javax.swing.GroupLayout(medecin);
        medecin.setLayout(medecinLayout);
        medecinLayout.setHorizontalGroup(
            medecinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medecinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(medecinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajoutPatients1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        medecinLayout.setVerticalGroup(
            medecinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medecinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajoutPatients1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.addTab("Médecins", medecin);

        ajoutDeSoins.setBackground(new java.awt.Color(255, 255, 255));
        ajoutDeSoins.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), null));

        dateSoin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateSoin.setText("Date");

        medecinSoin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        medecinSoin.setText("Médecin");

        patientSoin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        patientSoin.setText("Patient");

        actesSoin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        actesSoin.setText("Actes");

        ajouterSoin.setText("+ Ajouter");
        ajouterSoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterSoinActionPerformed(evt);
            }
        });

        infosPatient.setColumns(20);
        infosPatient.setRows(5);
        jScrollPane3.setViewportView(infosPatient);

        javax.swing.GroupLayout ajoutDeSoinsLayout = new javax.swing.GroupLayout(ajoutDeSoins);
        ajoutDeSoins.setLayout(ajoutDeSoinsLayout);
        ajoutDeSoinsLayout.setHorizontalGroup(
            ajoutDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutDeSoinsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajoutDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actesSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ajoutDeSoinsLayout.createSequentialGroup()
                        .addGroup(ajoutDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ajoutDeSoinsLayout.createSequentialGroup()
                                .addComponent(dateSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wDateActe, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                            .addGroup(ajoutDeSoinsLayout.createSequentialGroup()
                                .addComponent(medecinSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wMedeinActe)))
                        .addGap(40, 40, 40)
                        .addComponent(patientSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ajouterSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ajoutDeSoinsLayout.setVerticalGroup(
            ajoutDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajoutDeSoinsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ajoutDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wDateActe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ajoutDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajoutDeSoinsLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ajoutDeSoinsLayout.createSequentialGroup()
                        .addGroup(ajoutDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medecinSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wMedeinActe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actesSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(ajouterSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        listeDeSoins.setBackground(new java.awt.Color(255, 255, 255));
        listeDeSoins.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 255), null));

        jScrollPane1.setViewportView(listesoin);

        triSoin.setText("Trier par");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        consulterSoin.setText("Consulter");
        consulterSoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterSoinActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("De");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("A");

        jLabel4.setText("Afficher fiches");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("OK");

        modifierSoin.setText("Modifier");

        jButton1.setText("Toutes les fiches");

        javax.swing.GroupLayout listeDeSoinsLayout = new javax.swing.GroupLayout(listeDeSoins);
        listeDeSoins.setLayout(listeDeSoinsLayout);
        listeDeSoinsLayout.setHorizontalGroup(
            listeDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listeDeSoinsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listeDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(listeDeSoinsLayout.createSequentialGroup()
                        .addComponent(triSoin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listeDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listeDeSoinsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(listeDeSoinsLayout.createSequentialGroup()
                        .addGroup(listeDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(listeDeSoinsLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(listeDeSoinsLayout.createSequentialGroup()
                                .addGroup(listeDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(modifierSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(consulterSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 141, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        listeDeSoinsLayout.setVerticalGroup(
            listeDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listeDeSoinsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listeDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(triSoin)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listeDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listeDeSoinsLayout.createSequentialGroup()
                        .addGroup(listeDeSoinsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(DateArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(modifierSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consulterSoin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout soinLayout = new javax.swing.GroupLayout(soin);
        soin.setLayout(soinLayout);
        soinLayout.setHorizontalGroup(
            soinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(soinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajoutDeSoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listeDeSoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        soinLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ajoutDeSoins, listeDeSoins});

        soinLayout.setVerticalGroup(
            soinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(soinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajoutDeSoins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listeDeSoins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.addTab("Soins", soin);

        gh.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifier le Coût de l'Acte"));

        listeDesActes.setText("Choix de l'acte");

        listeActes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Entrer le nouveau coût");

        nouveauCoutActe.setText("jTextField5");

        jLabel5.setText("€");

        validerCout.setText("Valider");

        javax.swing.GroupLayout ghLayout = new javax.swing.GroupLayout(gh);
        gh.setLayout(ghLayout);
        ghLayout.setHorizontalGroup(
            ghLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ghLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ghLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validerCout, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listeDesActes)
                    .addComponent(listeActes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ghLayout.createSequentialGroup()
                        .addComponent(nouveauCoutActe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        ghLayout.setVerticalGroup(
            ghLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ghLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listeDesActes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listeActes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ghLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nouveauCoutActe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(validerCout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Créer un Acte"));

        listeDesActes1.setText("Nom de l'acte");

        jLabel6.setText("Coût de l'acte");

        CoutDuNouvelActe.setText("jTextField5");

        jLabel7.setText("€");

        validerCout1.setText("Valider");

        nomDuNouvelActe.setText("jTextField5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(validerCout1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listeDesActes1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CoutDuNouvelActe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(nomDuNouvelActe))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listeDesActes1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomDuNouvelActe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CoutDuNouvelActe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(validerCout1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Voir le Coût d'un Acte"));

        jLabel8.setText("Choisir un Acte");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane2.setViewportView(jTextPane1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("€");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ActesLayout = new javax.swing.GroupLayout(Actes);
        Actes.setLayout(ActesLayout);
        ActesLayout.setHorizontalGroup(
            ActesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ActesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ActesLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ActesLayout.setVerticalGroup(
            ActesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ActesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        menu.addTab("Actes", Actes);

        javax.swing.GroupLayout fenetreLayout = new javax.swing.GroupLayout(fenetre);
        fenetre.setLayout(fenetreLayout);
        fenetreLayout.setHorizontalGroup(
            fenetreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu)
        );
        fenetreLayout.setVerticalGroup(
            fenetreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        menu.getAccessibleContext().setAccessibleName("patient");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fenetre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fenetre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void importPatientFromXML() {

        

        LectureXML pat = new LectureXML("dossiers.xml");
        DossierMedical dm = pat.getDossier();
        for (int i = 0; i < dm.getFiches().size(); i++) {
            
            Patient p = new Patient(dm.getFiches().get(i).getPatient().getNom(), dm.getFiches().get(i).getPatient().getPrenom(),dm.getFiches().get(i).getPatient().getAdresse(), dm.getFiches().get(i).getPatient().getSecu());
            patients.add(p);
            
            int indexListepatient = listepatient.getSelectedIndex();
            dlmPat.addElement(patients.get(i).getNom() + " " + patients.get(i).getPrenom() + " / " + patients.get(i).getSecu());
            
        }
        listepatient.setModel(dlmPat);
    }


    private void ajouterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterPatientActionPerformed

        //patients.add(patient);
        Patient patient = new Patient(wnomPatient.getText(), wprenomPatient.getText(), wssPatient.getText(), wadresse.getText());
        patients.add(patient);

        int taille = 1;
        for (int i = 0; i < taille; i++) {

            dlmPat.addElement(patient.getNom() + " " + patient.getPrenom() + " / " + patient.getSecu());

        }
        taille++;

        listepatient.setModel(dlmPat);
        wnomPatient.setText(null);
        wprenomPatient.setText(null);
        wssPatient.setText(null);
        wadresse.setText(null);


    }//GEN-LAST:event_ajouterPatientActionPerformed

    private void ficheSoinPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficheSoinPatientActionPerformed

        int selectedIndex = menu.getSelectedIndex();
        selectedIndex = (selectedIndex + 2) % menu.getTabCount();
        menu.setSelectedIndex(selectedIndex);

        infosPatient.setText(listepatient.getSelectedValue().toString());

    //reste à faire un override de toString pour que chaque élément soit sur une ligne différente si possible

    }//GEN-LAST:event_ficheSoinPatientActionPerformed

    private void modifierPatient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierPatient1ActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                //On crée une nouvelle instance de notre JDialog
                dialog1 = new JDialog();
                dialog1.setLocationRelativeTo(null);
                dialog1.setSize(300, 250);//On lui donne une taille
                dialog1.setTitle("Modifier Patient"); //On lui donne un titre

                dialog1.setLayout(new BorderLayout());
                JButton valider = new JButton("Valider");
                JPanel boutons = new JPanel();
                boutons.setLayout(new FlowLayout());
                dialog1.add(boutons, BorderLayout.SOUTH);
                boutons.add(valider);

                JPanel infosPatient = new JPanel();

                infosPatient.setLayout(new BoxLayout(infosPatient, Y_AXIS));
                dialog.add(infosPatient, BorderLayout.CENTER);

                int res = listepatient.getSelectedIndex();
                JTextField nomModif = new JTextField();
                nomModif.setText((String) patients.get(res).getNom());
                patients.get(res).setNom(nomModif.getText());

                infosPatient.add(nomModif);

                dialog.setVisible(true);//On la rend visible

                infosPatient.setLayout(new BoxLayout(infosPatient,Y_AXIS));
                dialog1.add(infosPatient, BorderLayout.CENTER);
                res = listepatient.getSelectedIndex();
                
                nomModif = new JTextField();
                nomModif.setText((String)patients.get(res).getNom());
                
                prenomModif = new JTextField();
                prenomModif.setText((String)patients.get(res).getPrenom());
                
                nSSModif = new JTextField();
                nSSModif.setText((String)patients.get(res).getSecu());
                
                adresseModif = new JTextField();
                adresseModif.setText((String)patients.get(res).getAdresse());
                
                infosPatient.add(nomModif);
                infosPatient.add(prenomModif);
                infosPatient.add(nSSModif);
                infosPatient.add(adresseModif);
                              
                dialog1.setVisible(true);//On la rend visible
<<<<<<< HEAD

=======
>>>>>>> ae2c901a3daa0575d6a2e6177683673809aaf96d
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //On dit à l'application de se fermer lors du clic sur la croix

                valider.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        validerPatientModifActionPerformed(evt);
                    }
                });

            }
        });
    }//GEN-LAST:event_modifierPatient1ActionPerformed

<<<<<<< HEAD

   
    private void validerPatientModifActionPerformed(java.awt.event.ActionEvent evt){
=======
        //
    private void validerActionPerformed(java.awt.event.ActionEvent evt){
>>>>>>> ae2c901a3daa0575d6a2e6177683673809aaf96d
        patients.get(res).setNom(nomModif.getText());
        patients.get(res).setPrenom(prenomModif.getText());
        patients.get(res).setSecu(nSSModif.getText());
        patients.get(res).setAdresse(adresseModif.getText());
        
        dlmPat.remove(res);
        dlmPat.add(res, patients.get(res).getNom()+ " " + patients.get(res).getPrenom()+ " / " + patients.get(res).getSecu());
        listepatient.setModel(dlmPat);  
        
        dialog1.dispose();
<<<<<<< HEAD

=======
>>>>>>> ae2c901a3daa0575d6a2e6177683673809aaf96d
    }
    private void recherchePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recherchePatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recherchePatientActionPerformed

    private void consulterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterPatientActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                //On crée une nouvelle instance de notre JDialog
                dialog = new JDialog();
                dialog.setLocationRelativeTo(null);
                dialog.setSize(300, 250);//On lui donne une taille
                dialog.setTitle("Fiche Patient"); //On lui donne un titre

                dialog.setLayout(new BorderLayout());
                JButton retour = new JButton("Retour");
                JButton imprimer = new JButton("Imprimer");
                JPanel boutons = new JPanel();
                boutons.setLayout(new FlowLayout());
                dialog.add(boutons, BorderLayout.SOUTH);
                boutons.add(retour);
                boutons.add(imprimer);

                JPanel infosPatient = new JPanel();
                infosPatient.setLayout(new BoxLayout(infosPatient, Y_AXIS));
                dialog.add(infosPatient, BorderLayout.CENTER);

                int res = listepatient.getSelectedIndex();
                JLabel nom1 = new JLabel((String) patients.get(res).getNom());
                nom1.setFont(new Font("Serif", Font.PLAIN, 22));
                JLabel prenom1 = new JLabel((String) patients.get(res).getPrenom());
                prenom1.setFont(new Font("Serif", Font.PLAIN, 18));
                JLabel secu1 = new JLabel((String) patients.get(res).getSecu());
                secu1.setFont(new Font("Serif", Font.PLAIN, 15));
                JLabel adresse1 = new JLabel((String) patients.get(res).getAdresse());
                adresse1.setFont(new Font("Serif", Font.PLAIN, 15));
                JLabel vide = new JLabel(" ");      //Créer un espace entre les infos générales du patients et son adresse

                infosPatient.add(nom1);
                infosPatient.add(prenom1);
                infosPatient.add(secu1);
                infosPatient.add(vide);
                infosPatient.add(adresse1);

                dialog.setVisible(true);//On la rend visible
                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //On dit à l'application de se fermer lors du clic sur la croix

                retour.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        retourActionPerformed(evt);
                    }
                });

            }
        });
    }//GEN-LAST:event_consulterPatientActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {
        dialog.dispose();
    }

    private void ajouterMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterMedecinActionPerformed

        Medecin medecin = new Medecin(wnomMedecin.getText(), wprenomMedecin.getText(), wTelMedecin.getText(), wSpeMedecin.getText(), wIdentifiantMedecin.getText(), wMDPMedecin.getText());
        medecins.add(medecin);

        int taille = 1;
        for (int i = 0; i < taille; i++) {

            dlmMed.addElement(medecin.getNom() + " " + medecin.getPrenom() + " " + medecin.getSpecialite() + " " + medecin.getTel());
            //reste à faire la partie qui enregistre le médecin dans l'Xml mais j'ai peur de tout casser je verrai avec Julia
        }
        taille++;
        listemedecin.setModel(dlmMed);

        wnomMedecin.setText(null);
        wprenomMedecin.setText(null);
        wTelMedecin.setText(null);
        wSpeMedecin.setText(null);
        wIdentifiantMedecin.setText(null);
        wMDPMedecin.setText(null);
    }//GEN-LAST:event_ajouterMedecinActionPerformed

    private void consulterMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterMedecinActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                //On crée une nouvelle instance de notre JDialog
                JDialog dialog = new JDialog();
                dialog.setLocationRelativeTo(null);
                dialog.setSize(300, 200);//On lui donne une taille
                dialog.setTitle("Fiche Médecin"); //On lui donne un titre

                dialog.setLayout(new BorderLayout());

                dialog.setVisible(true);//On la rend visible

                setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //On dit à l'application de se fermer lors du clic sur la croix
            }
        });

    }//GEN-LAST:event_consulterMedecinActionPerformed

    private void modifierMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierMedecinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifierMedecinActionPerformed

    private void recherchePatient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recherchePatient1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recherchePatient1ActionPerformed

    private void consulterSoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterSoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consulterSoinActionPerformed

    private void wnomPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wnomPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wnomPatientActionPerformed

    private void wssPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wssPatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wssPatientActionPerformed

    private void wTelMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wTelMedecinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wTelMedecinActionPerformed

    private void ajouterSoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterSoinActionPerformed


    }//GEN-LAST:event_ajouterSoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Fenetre().setVisible(true);

            }
        });
    }

    int res;
    JTextField nomModif;
    JTextField prenomModif;
    JTextField nSSModif;
    JTextField adresseModif;
    JDialog dialog;
    JDialog dialog1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actes;
    private javax.swing.JTextField CoutDuNouvelActe;
    private javax.swing.JTextField DateArrivee;
    private javax.swing.JTextField Rechercher;
    private javax.swing.JLabel actesSoin;
    private javax.swing.JLabel adresse;
    private javax.swing.JLabel adresse1;
    private javax.swing.JPanel ajoutDeSoins;
    private javax.swing.JPanel ajoutPatients;
    private javax.swing.JPanel ajoutPatients1;
    private javax.swing.JButton ajouterMedecin;
    private javax.swing.JButton ajouterPatient;
    private javax.swing.JButton ajouterSoin;
    private javax.swing.JButton consulterMedecin;
    private javax.swing.JButton consulterPatient;
    private javax.swing.JButton consulterSoin;
    private javax.swing.JTextField dateDepart;
    private javax.swing.JLabel dateSoin;
    private javax.swing.JPanel fenetre;
    private javax.swing.JButton ficheSoinPatient;
    private javax.swing.JPanel gh;
    private javax.swing.JTextArea infosPatient;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JComboBox listeActes;
    private javax.swing.JPanel listeDePatients;
    private javax.swing.JPanel listeDeSoins;
    private javax.swing.JLabel listeDesActes;
    private javax.swing.JLabel listeDesActes1;
    private javax.swing.JScrollPane listePatients;
    private javax.swing.JScrollPane listePatients1;
    private javax.swing.JList listemedecin;
    private javax.swing.JList listepatient;
    private javax.swing.JList listesoin;
    private javax.swing.JPanel medecin;
    private javax.swing.JLabel medecinSoin;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JButton modifierMedecin;
    private javax.swing.JButton modifierPatient1;
    private javax.swing.JButton modifierSoin;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel nom1;
    private javax.swing.JTextField nomDuNouvelActe;
    private javax.swing.JTextField nouveauCoutActe;
    private javax.swing.JPanel patient;
    private javax.swing.JLabel patientSoin;
    private javax.swing.JLabel prenom;
    private javax.swing.JLabel prenom1;
    private javax.swing.JButton recherchePatient;
    private javax.swing.JButton recherchePatient1;
    private javax.swing.JPanel soin;
    private javax.swing.JLabel ss;
    private javax.swing.JLabel ss2;
    private javax.swing.JLabel triSoin;
    private javax.swing.JButton validerCout;
    private javax.swing.JButton validerCout1;
    private javax.swing.JTextField wDateActe;
    private javax.swing.JTextField wIdentifiantMedecin;
    private javax.swing.JTextField wMDPMedecin;
    private javax.swing.JTextField wMedeinActe;
    private javax.swing.JTextField wSpeMedecin;
    private javax.swing.JTextField wTelMedecin;
    private javax.swing.JTextField wadresse;
    private javax.swing.JTextField wnomMedecin;
    private javax.swing.JTextField wnomPatient;
    private javax.swing.JTextField wprenomMedecin;
    private javax.swing.JTextField wprenomPatient;
    private javax.swing.JTextField wssPatient;
    // End of variables declaration//GEN-END:variables
}
